codecov:
  strict_yaml_branch: dev
ignore:
  - "build"
  - "src/Tgstation.Server.Host/ClientApp"
  - "src/Tgstation.Server.Host/Database/Migrations"
  - "src/Tgstation.Server.Host/Database/Design"
  - "test"
  - "tools"
coverage:
  status:
    project:
      default:
        threshold: 0
        if_no_uploads: failure
        if_ci_failed: failure
comment:
  layout: "header, diff, changes"
